### ISSUE TITLE
应该是看了我的博客拉下来的源码

### ISSUE THREAD

**Issue by CiChui** [oec2003/MIPushCSharpSample#1]
原文地址：http://cichui.top
当时没时间做个Demo项目给小白看，就只放了一部分关键代码！
感谢你出这个Demo，不过还是建议把你所遇到的问题更完善进去，比如忽略SSL验证相关内容。
消息发送的多种方式，消息透传的应用等等。教程与Demo的含义在于让小白更快上手，更快理解！
以上只是建议。。。。。
如有需要可以协助完善项目！

**Comment by liguobao** [comment]
咨询一下...
这样的转换方式拿出来的DLL支持 dotnet core 2.0吗?
我们是不是可以一起来做一下?

**Comment by oec2003** [comment]
@CiChui 当时遇到问题一通查，可能是参考的你的代码，感谢

你的建议很好，有时间会逐步完善。

**Comment by oec2003** [comment]
@liguobao li

你可以在dotNET Core下试试是否可以正常编译

**Comment by liguobao** [comment]
谢谢了,我看到他们的Web API了,直接用Web API应该能满足我的需求.
